// Code generated by "stringer -type=Banned"; DO NOT EDIT.

package generate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BanRegister-1]
	_ = x[BanLogin-2]
	_ = x[BanComment-3]
	_ = x[BanPay-4]
}

const _Banned_name = "BanRegisterBanLoginBanCommentBanPay"

var _Banned_index = [...]uint8{0, 11, 19, 29, 35}

func (i Banned) String() string {
	i -= 1
	if i < 0 || i >= Banned(len(_Banned_index)-1) {
		return "Banned(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Banned_name[_Banned_index[i]:_Banned_index[i+1]]
}
